# Generated by Django 4.0.6 on 2022-09-13 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_users_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
